language: cpp

os:
  - linux
  - osx

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:canonical-qt5-edgers/ubuntu1204-qt5
      && sudo apt-get -qq update
      && sudo apt-get -qq install -y g++-4.9 libc6-i386 qtbase5-dev
      && export CXX="g++-4.9"
      ;
    else
         brew update > /dev/null
      && brew install homebrew/x11/freeglut
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      QTDIR="/opt/qt56";
    else
      QTDIR="/usr/local/opt/qt5";
    fi
  - export PATH="$QTDIR/bin:$PATH"
  - mkdir -p build
  - cd build
  - qmake -config release ..

script:
  - make -j2

